### ISSUE TITLE
Variants argument not recognized

### ISSUE THREAD

**Issue by iwan** [yfxie/active_storage_variantt#1]
Hi, i have a model
```
class Signature < ApplicationRecord
  belongs_to :ticket
  has_one_attached :image, variants: {
    trimmed: { trim: true }
  }
end
```

but i get this error:
```
irb(main):001:0> s=Signature.last
Traceback (most recent call last):
        3: from (irb):1
        2: from app/models/signature.rb:10:in `<main>'
        1: from app/models/signature.rb:12:in `<class:Signature>'
ArgumentError (unknown keyword: :variants)
irb(main):002:0>
```

**Comment by yfxie** [comment]
Sorry for my mistake.
The correct usage should be:

```ruby
class User < ActiveRecord::Base
  has_one_attached :avatar do |blob|
    blob.variant  :thumb, resize: "100x100"
    blob.variant :medium, resize: "300x300", monochrome: true
  end
end

class Gallery < ActiveRecord::Base
  has_many_attached :photos do |blob|
    blob.variant  :thumb, resize: "100x100"
    blob.variant :medium, resize: "300x300", monochrome: true
  end
end
```
 
README updated.
